test_experiment_date_or_test_experiment_name_list = '20220418'
control_type_string = [] 
minimum_fly_count = 8 
output_folder_name = []
do_comparisons_only = []
do_force = []
flyvisionbox_folder_path = '/groups/scicompsoft/home/taylora/flyvisionbox-home/flyvisionbox-data-test-2022-04-18'

batch_analysis(test_experiment_date_or_test_experiment_name_list, ...
               control_type_string, ...
               minimum_fly_count, ...
               output_folder_name, ...
               do_comparisons_only, ...
               do_force, ...
               flyvisionbox_folder_path)



